### ISSUE TITLE
장기 추이를 볼 수 있는 차트

### ISSUE THREAD

**Issue by pelly-ryu** [rocky112358/ram-price-tracker#1]
현재 7일까지 있는데, 더 길게 볼 수 있으면 좋겠어요

:)

**Comment by rocky112358** [comment]
1년치 데이터를 **1일 단위**로 반환하도록 백엔드 코드를 수정했습니다. `mode=one_year`로 요청하면 됩니다.

**Comment by pelly-ryu** [comment]
넹 감사합니다 일단 닫겠습니다
